table publisher_risk_scoring
	lineageTag: b0000006-0000-0000-0000-000000000000

	column publisher_id
		dataType: string
		lineageTag: b0000006-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: publisher_id

	column total_leads
		dataType: int64
		lineageTag: b0000006-0000-0000-0000-000000000002
		summarizeBy: sum
		sourceColumn: total_leads

	column approved_leads
		dataType: int64
		lineageTag: b0000006-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: approved_leads

	column fast_ttc_bot_leads
		dataType: int64
		lineageTag: b0000006-0000-0000-0000-000000000005
		summarizeBy: sum
		sourceColumn: fast_ttc_bot_leads

	column approval_rate_pct
		dataType: double
		lineageTag: b0000006-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: approval_rate_pct

	column risk_level
		dataType: string
		lineageTag: b0000006-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: risk_level

	column total_margin_vnd
		dataType: double
		lineageTag: b0000006-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: total_margin_vnd

	partition publisher_risk_scoring = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.Decompress(File.Contents(DataFolder & "gold\publisher_risk_scoring.csv.gz"), Compression.GZip), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"publisher_id", type text}, {"total_leads", Int64.Type}, {"approved_leads", Int64.Type}, {"approval_rate_pct", type number}, {"fast_ttc_bot_leads", Int64.Type}, {"total_margin_vnd", type number}, {"risk_level", type text}})
				in
				    #"Changed Type"

