"""
Publisher Cohort Analysis: Activation, Retention, Revenue Retention & LTV
Project: AP-TRIS

Business question
    Which publisher acquisition channels bring publishers who STAY and keep
    generating margin? Where should the Publisher Development team invest?

Definitions
    Cohort            : publishers grouped by registration month (join_date)
    Month index M+k   : months since registration (M+0 = registration month)
    Active            : >= 1 approved conversion in that month
    Activation rate   : % of a cohort active within M+0..M+1
    Logo retention    : % of the cohort active at M+k   (denominator = full cohort)
    Revenue retention : cohort margin at M+k / cohort margin at M+1 (first full month)
    LTV (k months)    : cumulative margin per REGISTERED publisher after k months

Input  : 01_data/sources/publisher_registry.csv.gz, publisher_monthly_activity.csv.gz
         (generated by 01_data/generate_publisher_history.py - simulated history)
Output : 03_analysis/outputs/cohort_*.csv and cohort_retention_heatmap.png
"""
import os

import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "01_data", "sources")
OUT = os.path.join(BASE, "03_analysis", "outputs")
LAST_MONTH = pd.Period("2026-09", "M")
MAX_K = 6


def load():
    reg = pd.read_csv(os.path.join(SRC, "publisher_registry.csv.gz"))
    act = pd.read_csv(os.path.join(SRC, "publisher_monthly_activity.csv.gz"))
    reg["cohort"] = pd.to_datetime(reg.join_date).dt.to_period("M")
    act["month"] = pd.PeriodIndex(act.month, freq="M")
    act = act.merge(reg[["publisher_id", "cohort", "traffic_channel"]], on="publisher_id")
    act["k"] = (act.month - act.cohort).apply(lambda x: x.n)
    # Data-quality rule: activity before the registration month is impossible -> report & exclude
    bad = act[act.k < 0]
    if len(bad):
        print(f"[DQ] {len(bad)} publisher-months dated before registration "
              f"({bad.publisher_id.nunique()} publishers) -> excluded; raise with Tech (join_date sync issue)")
    return reg, act[act.k >= 0]


def retention_matrix(reg, act, value="logo"):
    size = reg.groupby("cohort").size()
    if value == "logo":
        num = act.groupby(["cohort", "k"]).publisher_id.nunique().unstack()
        mat = num.div(size, axis=0) * 100
    else:  # revenue retention vs. M+1 (M+0 is a partial month)
        mar = act.groupby(["cohort", "k"]).gross_margin_vnd.sum().unstack()
        mat = mar.div(mar[1], axis=0) * 100
    # hide cells that are not observable yet (cohort too young)
    for c in mat.index:
        age = (LAST_MONTH - c).n
        mat.loc[c, [k for k in mat.columns if k > age]] = np.nan
    mat = mat[[k for k in mat.columns if k <= MAX_K]]
    mat.insert(0, "cohort_size", size)
    return mat


def main():
    os.makedirs(OUT, exist_ok=True)
    reg, act = load()
    print("=" * 78)
    print(">> PUBLISHER COHORT ANALYSIS (registrations Oct 2025 - Sep 2026)")
    print("=" * 78)
    print(f"Registered publishers: {len(reg):,} | status in Sep 2026: {reg.current_status.value_counts().to_dict()}")

    # 1. Logo retention matrix
    logo = retention_matrix(reg, act, "logo")
    print("\n[1] LOGO RETENTION - % of cohort with >= 1 approved conversion in month M+k")
    print(logo.round(1).fillna("").to_string())

    # 2. Revenue retention matrix
    rev = retention_matrix(reg, act, "revenue")
    print("\n[2] REVENUE RETENTION - cohort margin at M+k vs M+1 (=100)")
    print(rev.drop(columns="cohort_size").round(0).fillna("").to_string())

    # 3. By channel: activation, M+3 retention, LTV-3 (only cohorts old enough)
    mature = reg[reg.cohort <= LAST_MONTH - 3]
    first2 = act[act.k <= 1].groupby("publisher_id").size()
    m3 = act[act.k == 3].publisher_id.unique()
    ltv3 = act[act.k <= 3].groupby("publisher_id").gross_margin_vnd.sum()
    ch = mature.assign(activated=mature.publisher_id.isin(first2.index),
                       retained_m3=mature.publisher_id.isin(m3),
                       ltv3=mature.publisher_id.map(ltv3).fillna(0)) \
        .groupby("traffic_channel").agg(registered=("publisher_id", "count"),
                                        activation_pct=("activated", "mean"),
                                        retention_m3_pct=("retained_m3", "mean"),
                                        ltv3_per_registered_vnd=("ltv3", "mean"))
    ch[["activation_pct", "retention_m3_pct"]] *= 100
    ch = ch.sort_values("ltv3_per_registered_vnd", ascending=False)
    print("\n[3] BY ACQUISITION CHANNEL (cohorts Oct 2025 - Jun 2026, observable >= 3 months)")
    print(ch.round(1).to_string())

    # 4. Save outputs
    logo.to_csv(os.path.join(OUT, "cohort_logo_retention.csv"))
    rev.to_csv(os.path.join(OUT, "cohort_revenue_retention.csv"))
    ch.to_csv(os.path.join(OUT, "cohort_by_channel.csv"))
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        data = logo.drop(columns="cohort_size")
        fig, ax = plt.subplots(figsize=(9, 6))
        im = ax.imshow(data.values.astype(float), cmap="Blues", vmin=0, vmax=100, aspect="auto")
        ax.set_xticks(range(data.shape[1]), [f"M+{k}" for k in data.columns])
        ax.set_yticks(range(data.shape[0]), [f"{c} (n={n})" for c, n in zip(data.index.astype(str), logo.cohort_size)])
        for i in range(data.shape[0]):
            for j in range(data.shape[1]):
                v = data.values[i, j]
                if not np.isnan(v):
                    ax.text(j, i, f"{v:.0f}%", ha="center", va="center", fontsize=8,
                            color="white" if v > 55 else "#0F172A")
        ax.set_title("Publisher logo retention by registration cohort", loc="left", fontsize=12)
        ax.set_xlabel("Months since registration")
        fig.colorbar(im, ax=ax, label="% of cohort active")
        fig.tight_layout()
        fig.savefig(os.path.join(OUT, "cohort_retention_heatmap.png"), dpi=150)
        print(f"\n[OK] Heatmap -> {os.path.relpath(os.path.join(OUT, 'cohort_retention_heatmap.png'), BASE)}")
    except ImportError:
        pass

    # LTV curve by channel (cumulative margin per REGISTERED publisher, M+0..M+3)
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        cum = act[(act.k <= 3) & act.publisher_id.isin(mature.publisher_id)] \
            .groupby(["traffic_channel", "k"]).gross_margin_vnd.sum().unstack().cumsum(axis=1)
        cum = cum.div(mature.groupby("traffic_channel").size(), axis=0) / 1e6
        highlight = {"SEO Content Hub": "#0D9488", "Facebook Media Buyer": "#F59E0B"}
        fig, ax = plt.subplots(figsize=(8, 4.5))
        # end-of-line labels, nudged apart so they never overlap
        ends = cum.iloc[:, -1].sort_values()
        min_gap = (ends.max() - ends.min()) * 0.07
        label_y, prev = {}, -np.inf
        for chn, v in ends.items():
            prev = max(v, prev + min_gap)
            label_y[chn] = prev
        for chn, row in cum.iterrows():
            c = highlight.get(chn, "#CBD5E1")
            ax.plot(row.index, row.values, color=c, lw=2.5 if chn in highlight else 1.5,
                    marker="o", ms=5, zorder=3 if chn in highlight else 2)
            ax.text(3.08, label_y[chn], f"{chn}  {row.values[-1]:.2f}M", va="center", fontsize=8.5,
                    color="#0F172A" if chn in highlight else "#64748B",
                    fontweight="bold" if chn in highlight else "normal")
        ax.set_xticks([0, 1, 2, 3], ["M+0", "M+1", "M+2", "M+3"])
        ax.set_xlim(-0.1, 4.3)
        ax.set_ylabel("Cumulative margin per registered publisher (M VND)")
        ax.set_title("LTV by acquisition channel: Facebook activates fastest but earns least",
                     loc="left", fontsize=11)
        ax.grid(axis="y", color="#E2E8F0", lw=0.8)
        for sp in ("top", "right"):
            ax.spines[sp].set_visible(False)
        fig.tight_layout()
        fig.savefig(os.path.join(OUT, "cohort_ltv_by_channel.png"), dpi=150)
        plt.close(fig)
        print(f"[OK] LTV chart -> {os.path.relpath(os.path.join(OUT, 'cohort_ltv_by_channel.png'), BASE)}")
    except ImportError:
        pass

    print("\n[INSIGHTS]")
    best, worst = ch.index[0], ch.index[-1]
    print(f"  - Highest LTV-3 per registered publisher: {best} ({ch.loc[best, 'ltv3_per_registered_vnd']:,.0f} VND); "
          f"lowest: {worst} ({ch.loc[worst, 'ltv3_per_registered_vnd']:,.0f} VND)")
    act_rate, m3 = ch.activation_pct.mean(), ch.retention_m3_pct.mean()
    print(f"  - ~{100 - act_rate:.0f}% of registrants never activate; of those who do, only "
          f"~{m3 / act_rate * 100:.0f}% are still active at M+3 -> two levers: onboarding and early retention")
    fb = "Facebook Media Buyer"
    if fb in ch.index:
        print(f"  - {fb}: high activation ({ch.loc[fb, 'activation_pct']:.0f}%) but lowest LTV -> "
              f"fast to start, fast to leave (paid traffic stops when EPC drops)")
    print("  - Revenue retention > 100% after M+1: surviving publishers scale up -> retained publishers are worth "
          "more than their first month suggests")
    print("=" * 78)


if __name__ == "__main__":
    main()
